[project]
name = "mcp-sqlify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
